### ISSUE TITLE
rails 7 : error when loading caffeinate + caffeeinate webUI 

### ISSUE THREAD

**Issue by nmaisonneuve** [joshmn/caffeinate-marketing#6]
Hi there !, 

I have Rails 7.0.4 +puma 6 (Ubuntu 20.4)

1. 
I added caffeinate to my gemfile
bundle install gives me:

Using bootsnap 1.16.0
Using bundler 2.4.7
Using rails 7.0.4.3
-> Using caffeinate 2.4
Using native-package-installer 1.1.5
Using pkg-config 1.5.1
Using matrix 0.4.2
Using red-colo

but when I launch the rails 
[4129564] uninitialized constant Caffeinate
[4129564] /var/www/cityobs/releases/20230516040407/config/initializers/caffeinate.rb:4:in `<main>'
    /var/www/cityobs/shared/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `load'
    /var/www/cityobs/shared/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `block in load_config_initializer'
    /var/www/cityobs/shared/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:208:in `instrument'
    /var/www/cityobs/shared/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:666:in `load_config_initializer'
    /var/www/cityobs/shared/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb
    

I finally manage to find a workaround : removing "preload_apps!" in puma configuration do the tricks. but that's a bit weird and unwanted.
  
  
2. Then I add the gem "caffeinate_webui" + "mount Caffeinate::Webui => '/campaigns_ui' " on my  route  , I got the following error: 

rails aborted!
ArgumentError: A rack application must be specified
/Users/nmaisonneuve/dev/cityscoring/app_cityscoring/config/routes/admin.rb:8:in `block in draw'

=> 
is this gem tested on Rails 7 ? 
Is this gem loaded in a particular manner ?

Thanks

**Comment by nmaisonneuve** [comment]
@joshmn (sorry I should open an issue more on caffeinate gem)

**Comment by joshmn** [comment]
Hi! Sorry for the lat reply. Zelda has taken me away from developing for a bit.

That's very peculiar! Do you have Caffeinate also in your Gemfile?
